name: Greeting Template

on:
  workflow_call:
    inputs:
      name:
        required: true
        type: string
        description: 'The name of the person to greet'

jobs:
  greeting_job:
    runs-on: ubuntu-latest
    steps:
      - name: Greet the person
        run: echo "Hello, ${{ inputs.name }}!"
