name: Greeting Template

on:
  workflow_call:
    inputs:
      name:
        required: true
        type: string
        description: 'The name of the person to greet'
      script_path:
        required: true
        type: string
        description: 'The path to the python script'

jobs:
  greeting_job:
    runs-on: ubuntu-latest
    steps:
      - name: Greet the person
        run: echo "Hello, ${{ inputs.name }}!"
        
      - name: Run hello world script
        run: python ${{ inputs.script_path }}
