ame: Use Greeting Composite

on:
  workflow_dispatch:
    inputs:
      name:
        description: 'The name of the person to greet'
        required: true
        type: string
      script_path:
        description: 'The path to the python script'
        required: true
        type: string

jobs:
  call-greeting-composite:
    runs-on: ubuntu-latest
    steps:
      - uses: ./greetings/display-name.yml
        with:
          name: ${{ inputs.name }}
          script_path: ${{ inputs.script_path }}
